Lab3
Reqvel/ITandDDP-Labs pull request #3
Opened 2022-03-30 10:00 UTC by Reqvel

2022-04-04 09:30 UTC, katetushkan requested changes
Do like what u did, pls fix things that I mentioned and i'l give u 9. If u wanna upgrade add focus styles to ur buttons and links. Let me know what u wanna do.

2022-04-04 09:30 UTC, katetushkan commented on static/css/progress-bar.css
> +    width: 13.53px;
noooo, pls noooo, Don't use float numbers for px, browser engine can count it wrong

2022-04-04 09:30 UTC, katetushkan commented on static/css/progress-bar.css
> +        width: 9vw;
use rem, vw can be tricky on mobile phones, especially in Safari for now better use % and in the future new units will be available for correct usage of viewport.

2022-04-04 09:30 UTC, katetushkan commented on static/css/music-player.css
> +    width: 3vw;
same here, for vw, check at the end of the review, pls

2022-04-04 09:30 UTC, katetushkan commented on static/css/base.css
> +embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby,
use universal selector for it - `*`

2022-04-04 17:20 UTC, Reqvel commented
Did fix the issues.  Don't really know what to add on focus, so 9 is fine

2022-04-12 10:42 UTC, katetushkan approved these changes
`9` is urs.

2022-04-24 15:57 UTC, merged