Lab6
Reqvel/ITandDDP-Labs pull request #6
Opened 2022-05-13 14:27 UTC by Reqvel

Having a hard time deploying this project, so i included demo images

2022-05-16 12:19 UTC, katetushkan requested changes
Pls, try to deploy cuz I can't check it properly without it, maybe with GitHub or firebase it's the most basic ways.

2022-05-16 12:19 UTC, katetushkan commented on lab6/src/App.js
> +        </Routes>
Place it in a detached file.

2022-05-16 12:19 UTC, katetushkan commented on lab6/src/common/GetArtistsNames.js
> +    var names = ''
let.

2022-05-16 12:19 UTC, katetushkan commented on lab6/src/components/Header.jsx
> +      <div className="header">
maybe, if it's `header` than it should be `<header>` ?)

2022-05-16 12:19 UTC, katetushkan commented on lab6/src/components/Header.jsx
> +        </button>
Should be a separate component. with class `button`, and props, which is gonna decide how the classname gonna looks like 

```
interface IProps {
  className?: string;
  onClick?: React.MouseEventHandler<HTMLButtonElement | HTMLAnchorElement>;
  autoFocus?: boolean;
  value?: string;
  disabled?: boolean;
  type?: 'normal' | 'accent';
  to?: string;
}

class Button extends React.Component<IProps> {

  render() {
    const { onClick, className, children, autoFocus, value, disabled, type, to } = this.props;

    return (
      <>
        {to
        ? <Link
            to={to}
            className={clsx('button', {
              'button--normal': !type || type === 'normal',
              'button--accent': type === 'accent',
              'button--disabled': disabled,
            }, className)}
            onClick={onClick}
          >
            {children}
          </Link>
        : <button
            autoFocus={autoFocus}
            className={clsx('button', {
              'button--normal': !type || type === 'normal',
              'button--accent': type === 'accent',
              'button--disabled': disabled,
            }, className)}
            onClick={onClick}
            value={value}
            disabled={disabled}
          >
            {children}
          </button>
        }
      </>
    )
  }
}

export default Button;
```

Smth like this.

2022-05-16 12:19 UTC, katetushkan commented on lab6/src/components/MusicPlayerControls/NextBtn.jsx
> +
All ur buttons should be a '<Button/>' but u can manipulate its appearance w/ outer styles and children props, and behaviour with onClick callback

2022-05-16 14:25 UTC, Reqvel commented
alright i will try to deploy it, but i need ur email that's attached to ur Spotify account(i need it to add to devs) and Spotify Premium is required for full access

2022-05-17 05:47 UTC, Reqvel commented
deploy https://spotifee-99d72.web.app/

2022-05-17 12:42 UTC, katetushkan commented
> alright i will try to deploy it, but i need ur email that's attached to ur Spotify account(i need it to add to devs) and Spotify Premium is required for full access

So I can't login with my account by my own ?

2022-05-17 13:45 UTC, Reqvel commented
yes, u can, but the API will not respond to anything because your account is not in the list of developers. In order to properly deploy the app, I need the approval of the Spotify app review team. And they will not approve it :)

2022-05-20 22:46 UTC, closed without merging